library(data.table)
trees <- fread("my_tests/faib_tree_detail_subtest.csv")
plots <- fread("my_tests/faib_plot_header.csv")
cat("Trees:", nrow(trees), "\n")
cat("Unique SITE_IDENTIFIER:", uniqueN(trees$SITE_IDENTIFIER), "\n")
cat("Unique SPECIES:", paste(sort(unique(trees$SPECIES)), collapse=", "), "\n")
cat("BTOP Y:", sum(trees$BROKEN_TOP_IND == "Y", na.rm=TRUE), "\n")
cat("HEIGHT_SOURCE:", paste(unique(trees$HEIGHT_SOURCE), collapse=", "), "\n")
cat("MEAS_INTENSE:", paste(unique(trees$MEAS_INTENSE), collapse=", "), "\n")
cat("\nPlots:", nrow(plots), "\n")
cat("BEC_ZONE:", paste(sort(unique(plots$BEC_ZONE)), collapse=", "), "\n")
cat("Sites in trees matched in plots:", sum(unique(trees$SITE_IDENTIFIER) %in% unique(plots$SITE_IDENTIFIER)), "\n")
